//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAndSeriesBlog_Website.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Comment
    {
        public int CommentID { get; set; }
        public string Username { get; set; }
        public string Mail { get; set; }
        public string CommentContent { get; set; }
        public Nullable<int> CommentBlog { get; set; }
    
        public virtual Tbl_Blog Tbl_Blog { get; set; }
    }
}
